prevent_proxy_connections: false
listeners:
- query_port: 25565
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: true
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - queue
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 50
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 64
permissions:
  default: null
  admin: null
log_pings: false
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
player_limit: 9000
ip_forward: true
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: a5381114-b8ec-4dc6-ae4a-0992a270a33c
online_mode: true
forge_support: true
disabled_commands:
- bungee
- alert
- alertraw
- end
- find
- glist
- greload
- ip
- perms
- server
- send
- globalslots
- cleanmotd
- dq
- bperm
- bpermission
- bpermissions
- bperms
- luckpermsbungee
- queue
- queues
- lpb
servers:
  queue:
    motd: Queue Server
    address: 172.18.0.1:52223
    restricted: false
  main:
    motd: Main Server
    address: 172.18.0.1:43244
    restricted: false
